sudo: false

dist: trusty

language: cpp

compiler:
    - gcc
env:
    matrix:
        - CMAKE_BUILD_TYPE=Release
        - CMAKE_BUILD_TYPE=Debug 

addons:
  apt:
    sources:
        #- boost-latest
      #- ubuntu-toolchain-r-test
      # - llvm-toolchain-precise-3.8
    packages:
    - libopenmpi-dev
    - libboost-all-dev
    - doxygen
    - petsc-dev
    - libsundials-serial-dev
    - libparmetis-dev
    - libhdf5-openmpi-dev
    - libxerces-c-dev


before_script:
- mkdir $HOME/bin
# install XSD
- wget http://www.codesynthesis.com/download/xsd/3.3/linux-gnu/x86_64/xsd-3.3.0-x86_64-linux-gnu.tar.bz2
- tar -xjf xsd-3.3.0-x86_64-linux-gnu.tar.bz2
- export set XSD_ROOT=$PWD/xsd-3.3.0-x86_64-linux-gnu
  #- ln -s xsd-3.3.0-x86_64-linux-gnu/bin/xsd $HOME/bin/xsd
- rm -f xsd-3.3.0-x86_64-linux-gnu.tar.bz2
- ls $XSD_ROOT
# install Python Amara
  #- pip install --user "python-dateutil==1.5"
  #- easy_install --user "Amara==1.2.0.2"
  #- pip install --user "rdflib==2.4.2"
  #- pip install --user lxml
# install VTK
#- wget http://www.vtk.org/files/release/5.10/vtk-5.10.1.tar.gz
#- tar zxf vtk-5.10.1.tar.gz
#- rm -f vtk-5.10.1.tar.gz
#- cd VTK5.10.1
#- cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$HOME . 
#- make
#- make install
#- cd ..
- uname -a
- printenv
- g++ --version 2>&1 | grep g++
- gcov --version | grep gcov
- grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
- doxygen --version

script:
- mkdir build
- cd build
- cmake -DChaste_USE_VTK=OFF -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..
  #- cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..
- make -j2
- ctest -j2 --output-on-failure


notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
